# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

dist: xenial
addons:
    apt:
        update: true
        sources:
        - sourceline: 'ppa:opencpu/imagemagick'
        - sourceline: 'ppa:ubuntugis/ppa'
        packages:
        - libmagick++-dev
        - librsvg2-dev
        - libwebp-dev
        - libpoppler-cpp-dev
        - libtesseract-dev
        - libleptonica-dev
        - tesseract-ocr-eng
        - r-cran-rgdal
        - libfftw3-dev
        - cargo
    snaps:
        - name: gifski
        confinement: classic
        channel: edge
