# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

warnings_are_errors: false

addons:
  apt:
    update: true
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - libfftw3-dev
      - cargo
      - gsfonts

cache:
    # Main R library    
    packages: true
